on:
  push:
    branches: [main]
    paths: [ "web/**", "docs/**" ]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - run: nix develop -c deploy
