on:
  push:
    branches: [main]
    paths: ["docs/**"]
jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: docs
        env:
          WEB_ADMIN_DEPLOY_KEY: ${{secrets.WEB_ADMIN_DEPLOY_KEY}}
          WEB_ADMIN_HOST: ${{secrets.WEB_ADMIN_HOST}}
        run: nix develop -c deploy-docs
