on:
  push:
    branches: [main]
    paths: ["web/**"]
jobs:
  web:
    name: web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: web
        env:
          WEB_ADMIN_DEPLOY_KEY: ${{secrets.WEB_ADMIN_DEPLOY_KEY}}
          WEB_ADMIN_API_KEY: ${{secrets.WEB_ADMIN_API_KEY}}
          WEB_ADMIN_API_URL: ${{secrets.WEB_ADMIN_API_URL}}
          WEB_ADMIN_HOST: ${{secrets.WEB_ADMIN_HOST}}
        run: nix run .#deploy-web
